In [2]:
# Importing necessary libraries
import pandas as pd

# Given data
starting_price = 90.31  # current price of UPRO
total_funds = 3587  # total available funds
decline_percentage = 0.20  # maximum price decline (20%)
price_steps = [90, 89, 87, 85, 83, 81, 79, 77, 75, 73]  # a 20% decrease in price broken into intervals
shares_per_step = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # incremental share increase at each level

# Initialize variables for tracking
remaining_funds = total_funds
purchases = []

# Calculate total cost at each step
for i, price in enumerate(price_steps):
    shares = shares_per_step[i]
    cost = price * shares
    if remaining_funds >= cost:
        purchases.append((price, shares, cost))
        remaining_funds -= cost
    else:
        break  # stop if we run out of funds

# Create a DataFrame to display the results
df = pd.DataFrame(purchases, columns=["Price", "Shares", "Total Cost"])

# Round the "Total Cost" and "Remaining Funds" columns to the nearest whole dollar
df["Total Cost"] = df["Total Cost"].round(0).astype(int)
df["Remaining Funds"] = total_funds - df["Total Cost"].cumsum()
df["Remaining Funds"] = df["Remaining Funds"].round(0).astype(int)

# Display the DataFrame
df

   Price  Shares  Total Cost  Remaining Funds
0     90       1          90             3497
1     89       2         178             3319
2     87       3         261             3058
3     85       4         340             2718
4     83       5         415             2303
5     81       6         486             1817
6     79       7         553             1264
7     77       8         616              648